name: "💡 Sugestão"
description: Sugerir uma melhoria ou novo recurso
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
